[package]
name = "sb_dice"
version = "0.1.0"
edition = "2024"

[dependencies]
swc_core = { version = "55.0", features = ["ecma_parser", "ecma_ast", "ecma_visit", "ecma_codegen", "common"] }
serde_json = "1.0"
